Update workflows

diff --git a/.github/workflows/gen-doc.yml b/.github/workflows/gen-doc.yml
--- a/.github/workflows/gen-doc.yml
+++ b/.github/workflows/gen-doc.yml
@@ -24,8 +24,11 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt
-
+        python -m pip install sphinx sphinx-autodoc-typehints python-docs-theme setuptools
+        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+        python setup.py sdist bdist_wheel || (echo "Failed to build wheel package" && exit 1)
+        pip install dist/loggingpython-*-py3-none-any.whl || (echo "Failed to install wheel package" && exit 1)
+  
     - name: Build HTML documentation
       run: |
         sphinx-build -b html doc_sphinx/source doc_sphinx/build
